# Generated by Django 4.1.6 on 2023-02-28 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=20)),
                ('BrandEnglish', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantee', models.CharField(max_length=200)),
                ('guarantee_percent', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('guarantee_price', models.CharField(blank=True, default='0', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ci', 'cash_in'), ('co', 'cash_out'), ('tr', 'transfer')], max_length=8)),
                ('price', models.PositiveIntegerField()),
                ('code', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('count_sell', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('code', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product-img/')),
                ('price', models.FloatField(default=0)),
                ('off_percent', models.IntegerField(blank=True, default=0, null=True)),
                ('club_point', models.IntegerField(blank=True, default=0, null=True)),
                ('hashtag', models.TextField(blank=True, max_length=60, null=True)),
                ('point', models.PositiveSmallIntegerField(default=0)),
                ('Sale', models.BooleanField()),
                ('sale_price', models.CharField(blank=True, max_length=35, null=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_edited', models.DateField(auto_now=True)),
                ('gender', models.BooleanField(default=False)),
                ('locations', models.CharField(blank=True, max_length=150, null=True)),
                ('season', models.CharField(blank=True, max_length=150, null=True)),
                ('Fnote', models.CharField(blank=True, max_length=250, null=True)),
                ('Mnote', models.CharField(blank=True, max_length=250, null=True)),
                ('Lnote', models.CharField(blank=True, max_length=250, null=True)),
                ('CountryMade', models.CharField(blank=True, max_length=150, null=True)),
                ('YearMade', models.CharField(blank=True, max_length=150, null=True)),
                ('Capacity', models.CharField(blank=True, max_length=150, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.category')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.color')),
                ('guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.guarantee')),
            ],
        ),
    ]
