# Generated by Django 4.1.6 on 2023-02-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gift',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
