# Generated by Django 4.1.6 on 2023-02-28 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_gift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='product-img/detail/')),
                ('product', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
