# Generated by Django 4.1.6 on 2023-02-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ManyToManyField(default=1, to='Product.product'),
        ),
    ]
