# Generated by Django 4.1.6 on 2023-03-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_remove_productimages_product_productimages_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Capacity',
        ),
        migrations.AddField(
            model_name='product',
            name='Capacity1',
            field=models.CharField(blank=True, default=50, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Capacity2',
            field=models.CharField(blank=True, default=50, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Capacity3',
            field=models.CharField(blank=True, default=50, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Capacity4',
            field=models.CharField(blank=True, default=50, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Capacity5',
            field=models.CharField(blank=True, default=50, max_length=150, null=True),
        ),
    ]
