# Generated by Django 3.1 on 2023-03-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_auto_20230312_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
