# Generated by Django 3.1 on 2023-03-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_auto_20230312_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_percent',
            new_name='sale_price',
        ),
    ]
