# Generated by Django 4.1.7 on 2023-03-11 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0010_alter_brand_id_alter_category_id_alter_color_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Wpay', 'Wpay'), ('Processing', 'Processing'), ('Sended', 'Sended'), ('Delivered', 'Delivered'), ('Dispatched', 'Dispatched'), ('Canceled', 'Canceled')], default='Wpay', max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ci', 'cash_in'), ('co', 'cash_out'), ('tr', 'transfer')], max_length=8)),
                ('price', models.CharField(max_length=30)),
                ('code', models.CharField(blank=True, max_length=36, null=True)),
                ('description', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstuser', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.TextField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=40, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=35, null=True)),
                ('last_name', models.CharField(blank=True, max_length=35, null=True)),
                ('totalprice', models.CharField(blank=True, max_length=35, null=True)),
                ('offprice', models.CharField(blank=True, max_length=35, null=True)),
                ('offpercent', models.CharField(blank=True, max_length=35, null=True)),
                ('sendcost', models.CharField(blank=True, max_length=35, null=True)),
                ('count', models.CharField(blank=True, max_length=10, null=True)),
                ('extramobile', models.CharField(blank=True, max_length=15, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('tracking', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Wpay', 'Wpay'), ('Processing', 'Processing'), ('Sended', 'Sended'), ('Delivered', 'Delivered'), ('Dispatched', 'Dispatched'), ('Canceled', 'Canceled')], default='Wpay', max_length=20)),
                ('season', models.CharField(blank=True, max_length=30, null=True)),
                ('explain', models.TextField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('tax', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
