# Generated by Django 4.1.7 on 2023-03-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ordermanagement',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordermanagement',
            name='sended',
            field=models.BooleanField(default=False),
        ),
    ]
