# Generated by Django 4.1.7 on 2023-03-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_ordermanagement_email_ordermanagement_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermanagement',
            name='extramobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ordermanagement',
            name='tax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordermanagement',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
