# Generated by Django 3.1 on 2023-03-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20230312_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variety',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
